package lk.ac.ruhuna.dcs.cvmanagement.shared.audit;

/** Stable event names for auditable business and CV lifecycle actions. */
public enum AuditEventType {
    COMPANY_CREATED,
    COMPANY_UPDATED,
    COMPANY_DELETED,
    INTERNSHIP_REQUEST_CREATED,
    INTERNSHIP_REQUEST_UPDATED,
    INTERNSHIP_REQUEST_DELETED,
    INTERNSHIP_REQUIRED_SKILL_ADDED,
    INTERNSHIP_REQUIRED_SKILL_REMOVED,
    INTERNSHIP_REQUIRED_SKILLS_REPLACED,
    CV_PREVIEW_GENERATED,
    CV_GENERATION_FAILED,
    CV_SAVED,
    CV_UPDATED,
    CV_DOWNLOADED_BY_STUDENT,
    CV_DOWNLOADED_BY_ADMIN,
    CV_FILE_UNAVAILABLE,
    CANDIDATE_FILTER_RUN_CREATED
}
