spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER}
      secret: ${JWT_SECRET}
    cors:
      allowed-origins: ${FRONTEND_ORIGIN}
  email:
      mode: smtp
      from: ${APP_EMAIL_FROM}

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    lk.ac.ruhuna.dcs.cvmanagement: INFO
