-- Run with a restricted local database account after the Newman collection.
-- Expected: at least one row for each event type generated by the acceptance run.
SELECT event_type, outcome, severity, COUNT(*) AS event_count
FROM public.audit_events
WHERE event_type IN (
    'AUTH_LOGIN_FAILED',
    'AUTH_ADMIN_LOGIN_SUCCEEDED',
    'AUTH_LOGOUT_SUCCEEDED'
)
GROUP BY event_type, outcome, severity
ORDER BY event_type;

-- Must return zero. Metadata must never contain common credential/OTP keys.
SELECT COUNT(*) AS forbidden_metadata_rows
FROM public.audit_events
WHERE metadata ?| ARRAY[
    'password', 'newPassword', 'confirmPassword', 'otp', 'otpCode',
    'accessToken', 'refreshToken', 'authorization'
];

-- Correlation coverage for the acceptance window.
SELECT COUNT(*) FILTER (WHERE correlation_id IS NOT NULL) AS correlated,
       COUNT(*) AS total
FROM public.audit_events
WHERE occurred_at >= CURRENT_TIMESTAMP - INTERVAL '30 minutes';
